### ISSUE TITLE
优化Table展示样式

### ISSUE THREAD

**Issue by cnmade** [cnmade/bsmi-kb#26]
参考mce编辑器后台的css样式
```css
table {
    border-collapse: collapse
}

table:not([cellpadding]) td,table:not([cellpadding]) th {
    padding: .4rem
}

table[border]:not([border="0"]):not([style*=border-width]) td,table[border]:not([border="0"]):not([style*=border-width]) th {
    border-width: 1px
}

table[border]:not([border="0"]):not([style*=border-style]) td,table[border]:not([border="0"]):not([style*=border-style]) th {
    border-style: solid
}

table[border]:not([border="0"]):not([style*=border-color]) td,table[border]:not([border="0"]):not([style*=border-color]) th {
    border-color: #ccc
}

figure {
    display: table;
    margin: 1rem auto
}

figure figcaption {
    color: #999;
    display: block;
    margin-top: .25rem;
    text-align: center
}

hr {
    border-color: #ccc;
    border-style: solid;
    border-width: 1px 0 0 0
}

code {
    background-color: #e8e8e8;
    border-radius: 3px;
    padding: .1rem .2rem
}
```
